name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches:
    - arenikun/coverity_local_test
  pull_request:
  workflow_dispatch:
    inputs:
      DPCPP_VERSION:
        description: "DPCPP version to use"
        type: string


permissions: read-all

env:
  no_proxy: "127.0.0.1,localhost,apt.repos.intel.com,mlpc.intel.com,*.intel.com"

jobs:
  coverity:
    runs-on: PVC
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install Intel graphics drivers
        uses: ./.github/actions/install-intel-graphics
        with:
          GPU: PVC
          IGC: ROLLING

      - name: Install DPC++
        uses: ./.github/actions/install-dpcpp
        with:
          DPCPP_RELEASE: RELEASE
          DPCPP_VERSION: ${{ inputs.DPCPP_VERSION }}
          GPU: PVC
          IGC: ROLLING

      - name: Setup virtual environment
        shell: bash
        run: |
          # Install cmake and ninja if not already available
          if ! command -v cmake &> /dev/null || ! command -v ninja &> /dev/null; then
            echo "Installing cmake and/or ninja..."
            sudo apt update
            sudo apt install -y cmake ninja-build
          else
            echo "cmake and ninja already available"
          fi
          . setvars.sh
          export IGC_ExtraOCLOptions="-cl-intel-256-GRF-per-thread"
          export SYCL_PROGRAM_COMPILE_OPTIONS="-ze-opt-large-register-file -gline-tables-only"
          export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
          export IGC_VectorAliasBBThreshold=100000000000
          # Persist environment variables to following steps 
          env >> $GITHUB_ENV
          which $CXX
          $CXX --version
          sycl-ls

      - name: Build
        shell: bash
        run: |
          cmake -G Ninja  \
            -DCUTLASS_ENABLE_SYCL=ON \
            -DDPCPP_SYCL_TARGET=intel_gpu_pvc \
            -DCMAKE_CXX_FLAGS="-Werror" \
            -DCUTLASS_SYCL_RUNNING_CI=ON

      - uses: vapier/coverity-scan-action@main
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          command: cmake --build .
          dry_run: true
          project: intel/sycl-tla
          working-directory: ''
